import type { Vraag } from '../types'

// Extra ECHTE tentamenvragen, geëxtraheerd uit het tentamen 15-6-2023 en het
// hertentamen 27-6-2024. bron='pdf' → tellen mee voor gewicht en zijn standaard
// zichtbaar. Filterbaar op jaar via bronCategorie.
const mc = (q: Omit<Vraag, 'type' | 'bron'>): Vraag => ({ ...q, type: 'mc', bron: 'pdf' })

export const extraVragen: Vraag[] = [
  // ===================== DEEL I =====================
  mc({
    id: 'x-2024-pdca', deel: 1, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.1', difficulty: 'gemiddeld',
    stam: 'Je geeft je product-idee op maar houdt je verkoopkanalen aan om door te zoeken naar een winstgevend product. Bij welke stap van de PDCA-cyclus past dit het beste?',
    opties: [{ id: 'a', tekst: 'P (Plan)' }, { id: 'b', tekst: 'D (Do)' }, { id: 'c', tekst: 'C (Check)' }, { id: 'd', tekst: 'A (Act)' }],
    juistAntwoord: 'd',
    uitleg: 'Antwoord d (Act). Bedenken/leveranciers/kanalen opzetten = Plan + Do. Perioderesultaat berekenen = Check. Het besluit om koers te wijzigen n.a.v. die check is Act.',
    hints: ['PDCA: Plan → Do → Check → Act.', 'Een besluit nemen ná het evalueren van resultaten = welke letter?'],
  }),
  mc({
    id: 'x-2023-tactisch', deel: 1, bronCategorie: 'tentamen-2023', bronLabel: 'Tentamen 2023 vr.1', difficulty: 'gemiddeld',
    stam: 'Een voorbeeld van tactische planning is:',
    opties: [
      { id: 'a', tekst: 'verandering van een functionele in een marktgerichte organisatiestructuur' },
      { id: 'b', tekst: 'vaststellen op welk soort klanten de verkopen zich moeten richten' },
      { id: 'c', tekst: 'een productieplanning maken wanneer bepaalde producten te produceren' },
    ],
    juistAntwoord: 'a',
    uitleg: 'Antwoord a. De organisatiestructuur (her)inrichten is tactisch. Klantkeuze/product-marktcombinaties = strategisch; productieplanning korte termijn = operationeel.',
    hints: ['Structuur inrichten = middellange termijn = tactisch.', 'Klantkeuze = strategisch; korte-termijn productieplan = operationeel.'],
  }),
  mc({
    id: 'x-2023-pdca-count', deel: 1, bronCategorie: 'tentamen-2023', bronLabel: 'Tentamen 2023 vr.2', difficulty: 'lastig',
    stam: 'Activiteiten: (1) verkoper op cursus sturen, (2) verkoopprijsverschillen berekenen, (3) omzet uitsplitsen naar productgroepen, (4) verkoopteam versterken, (5) verkoopcijfers concurrent bestuderen om te beoordelen, (6) promotie van producten staken. Hoeveel horen bij C (Check) en hoeveel bij A (Act)?',
    opties: [
      { id: 'a', tekst: 'twee in C, drie in A' }, { id: 'b', tekst: 'twee in C, vier in A' },
      { id: 'c', tekst: 'drie in C, twee in A' }, { id: 'd', tekst: 'drie in C, drie in A' },
    ],
    juistAntwoord: 'd',
    uitleg: 'Antwoord d. Check (analyseren/vergelijken): verschillen berekenen (2), omzet uitsplitsen (3), concurrent bestuderen om te beoordelen (5). Act (handelen): cursus (1), team versterken (4), promotie staken (6).',
    hints: ['Check = meten/analyseren/vergelijken. Act = concrete acties n.a.v. de analyse.', 'Deel de 6 activiteiten in twee hoopjes: "meten/beoordelen" vs "ingrijpen".'],
  }),
  mc({
    id: 'x-2024-arbeidsspec', deel: 1, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.6', difficulty: 'lastig',
    stam: 'Marco: 2.500 fietsbanden + 500 autobanden/week (20u elk), €50/u. Toni: 2.400 fietsbanden + 625 autobanden/week (20u elk), €60/u. Na specialisatie maakt Marco alleen fietsbanden, Toni alleen autobanden; totale aantallen gelijk, uren flexibel. Totale loonkostenbesparing?',
    opties: [{ id: 'a', tekst: '€248' }, { id: 'b', tekst: '€280' }, { id: 'c', tekst: '€300' }, { id: 'd', tekst: '€580' }],
    juistAntwoord: 'b',
    uitleg: 'Antwoord b. Marco 125 fietsbanden/u, Toni 31,25 autobanden/u. Nieuw: Marco 4.900 fietsbanden /125 = 39,2u × €50 = €1.960; Toni 1.125 autobanden /31,25 = 36u × €60 = €2.160 → €4.120. Oud: 40u×€50 + 40u×€60 = €4.400. Besparing €280.',
    hints: ['Bereken eerst de productiviteit per uur per product per persoon.', 'Verdeel de nieuwe totalen over wie het snelst is → benodigde uren × uurloon.', 'Oude kosten = 80u totaal; vergelijk met de nieuwe som.'],
  }),
  mc({
    id: 'x-2024-loonkosten-verschuiving', deel: 1, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.10', difficulty: 'lastig',
    stam: 'Mei: falafel- én shoarmabroodjes (door elkaar gebakken op één bakplaat); je loon = helft van (opbrengst − kosten). Juni: alléén falafel (10.000 stuks). Welke stelling klopt over de loonkosten?',
    opties: [
      { id: 'a', tekst: 'Net als mei zijn de loonkosten in juni direct.' },
      { id: 'b', tekst: 'Net als mei zijn de loonkosten in juni indirect.' },
      { id: 'c', tekst: 'In mei direct, in juni indirect.' },
      { id: 'd', tekst: 'In mei indirect, in juni direct.' },
    ],
    juistAntwoord: 'd',
    uitleg: 'Antwoord d. Loonkosten blijven variabel (hangen aan de verkopen). In mei twee productgroepen + indirecte bakplaatkosten → niet direct toewijsbaar (indirect). In juni één product → wél direct toewijsbaar.',
    hints: ['Met meerdere producten op één bakplaat: is het loon aan één product toe te wijzen?', 'Bij één productgroep wordt alles direct toewijsbaar.'],
  }),
  mc({
    id: 'x-2024-fiscaal-omega', deel: 1, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.7', difficulty: 'berucht',
    stam: 'Alpha (100% VV, 8% rente) en Omega (75% VV, 6% rente) hebben gelijk balanstotaal en gelijke brutowinst. Omega rekent ook opportunity costs over EV. A. Fiscale winst gelijk als EV-rente Omega 10% is. B. Bedrijfseconomische winst gelijk als EV-rente Omega 14% is.',
    opties: [{ id: 'a', tekst: 'A en B juist' }, { id: 'b', tekst: 'A juist, B onjuist' }, { id: 'c', tekst: 'A onjuist, B juist' }, { id: 'd', tekst: 'A en B onjuist' }],
    juistAntwoord: 'c',
    uitleg: 'Antwoord c. Fiscaal telt alleen VV-rente: Omega 0,75A×6% = 0,045A, Alpha A×8% = 0,08A → verschillend, dus A onjuist. Bedrijfseconomisch telt totale vermogenskosten: Alpha 8%. Omega = 0,045A + 0,25A×14% = 0,08A = ook 8% → B juist.',
    hints: ['Fiscaal: alleen rente over vreemd vermogen aftrekbaar.', 'Bedrijfseconomisch: óók rente over eigen vermogen. Zet de totale vermogenskosten gelijk.'],
  }),
  mc({
    id: 'x-2024-nietfin', deel: 1, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.2', difficulty: 'gemiddeld',
    stam: 'Waarom naast financiële óók niet-financiële indicatoren in de interne rapportage?',
    opties: [
      { id: 'a', tekst: 'Ze helpen ontwikkelingen vroegtijdig te signaleren die pas later financieel tot uiting komen.' },
      { id: 'b', tekst: 'Ze zijn altijd objectiever dan financiële indicatoren.' },
      { id: 'c', tekst: 'Ze zijn verplicht volgens de jaarrekeningwet.' },
      { id: 'd', tekst: 'Ze vervangen de financiële indicatoren volledig.' },
    ],
    juistAntwoord: 'a',
    uitleg: 'Antwoord a. Niet-financiële indicatoren hebben een langetermijnperspectief en signaleren vroeg; financiële geven vooral uitsluitsel over de korte termijn (achteraf).',
    hints: ['Financieel = achteraf/korte termijn. Niet-financieel = ?'],
  }),
  mc({
    id: 'x-2023-bsc', deel: 1, bronCategorie: 'tentamen-2023', bronLabel: 'Tentamen 2023 vr.3', difficulty: 'gemiddeld',
    stam: 'De divisie past de balanced scorecard toe. Dat blijkt vooral uit:',
    opties: [
      { id: 'a', tekst: 'aandacht voor financiële én niet-financiële doelen die op korte termijn moeten worden gehaald' },
      { id: 'b', tekst: 'vier samenhangende perspectieven die de strategie communiceren' },
      { id: 'c', tekst: 'negen aandachtsgebieden over de organisatie en haar resultaten' },
    ],
    juistAntwoord: 'b',
    uitleg: 'Antwoord b. De BSC kent vier samenhangende perspectieven die de strategie bewaken (balans korte/lange termijn). Negen aandachtsgebieden = EFQM/INK-model.',
    hints: ['Hoeveel perspectieven kent de balanced scorecard?', 'Negen aandachtsgebieden hoort bij het INK/EFQM-model, niet de BSC.'],
  }),

  // ===================== DEEL II =====================
  mc({
    id: 'x-2024-afval-iskp', deel: 2, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.9', difficulty: 'lastig',
    stam: 'Krentebollen: 2.000 stuks, €1.000 kosten, 3% afval (geheel onvermijdbaar). Croissants: 3.000 stuks, €1.500 kosten, 6% afval (half vermijdbaar). De ISKP van een krentebol is t.o.v. een croissant:',
    opties: [{ id: 'a', tekst: 'hoger' }, { id: 'b', tekst: 'gelijk' }, { id: 'c', tekst: 'lager' }],
    juistAntwoord: 'a',
    uitleg: 'Antwoord a. Krentebol: alle €1.000 onvermijdbaar → €1.000/2.000 = €0,50. Croissant: vermijdbaar = ½×6%×€1.500 = €45 gaat naar resultatenrekening → (€1.500−€45)/3.000 = €0,485. €0,50 > €0,485.',
    hints: ['Vermijdbare afval → resultatenrekening (eruit). Onvermijdbaar → in de kostprijs.', 'Bereken per product: (kosten − vermijdbaar deel) ÷ aantal.'],
  }),
  mc({
    id: 'x-2024-overcapaciteit', deel: 2, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.11', difficulty: 'berucht',
    stam: 'Normale productie 100.000/periode; piek +48.000; onderhoud vereist +10.000. Machines verkrijgbaar in 120.000 / 180.000 / 240.000. Ze koopt 180.000. Waarin is geïnvesteerd?',
    opties: [
      { id: 'a', tekst: 'rationele overcapaciteit van 32.000' },
      { id: 'b', tekst: 'irrationele overcapaciteit van 32.000' },
      { id: 'c', tekst: 'rationele 58.000 + irrationele 22.000' },
      { id: 'd', tekst: 'rationele overcapaciteit van 80.000' },
    ],
    juistAntwoord: 'd',
    uitleg: 'Antwoord d. Vereist = 100.000+48.000+10.000 = 158.000. Kleinste beschikbare machine die dat dekt = 180.000 → onvermijdbaar = rationeel. Overcapaciteit boven normale productie = 180.000−100.000 = 80.000, geheel rationeel.',
    hints: ['Bereken de totaal vereiste capaciteit (normaal + piek + onderhoud).', 'Welke machinemaat dekt dat net? Die keuze is onvermijdbaar = rationeel.', 'Overcapaciteit = machinemaat − normale productie.'],
  }),
  mc({
    id: 'x-2024-iskp-vkc', deel: 2, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.12', difficulty: 'berucht',
    stam: 'Eerste periode. Perioderesultaat bij ISKP is exact gelijk aan dat bij variabelekostencalculatie. Welke stelling is het meest compleet?',
    opties: [
      { id: 'a', tekst: 'werkelijke productie = normale productie' },
      { id: 'b', tekst: 'werkelijke productie = verkopen' },
      { id: 'c', tekst: 'normale productie = verkopen' },
      { id: 'd', tekst: 'productie, normale productie en verkopen allemaal gelijk' },
    ],
    juistAntwoord: 'b',
    uitleg: 'Antwoord b. Verschil ISKP − VKC = (W−V)×C/N. Voor gelijkheid (met C>0) moet W=V: er worden geen constante kosten op de balans geactiveerd. De normale productie speelt geen rol.',
    hints: ['Het verschil tussen de methoden zit in geactiveerde constante kosten in voorraad.', 'Verschil = (Werkelijk − Verkopen) × C/N. Wanneer is dat nul?'],
  }),
  mc({
    id: 'x-2024-vkc-vk', deel: 2, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.14', difficulty: 'gemiddeld',
    stam: 'VKC. Verkopen 12.500, verkoopprijs €25, constante kosten €40.000, perioderesultaat €80.000 (voordelig). Variabele kosten per stuk?',
    opties: [{ id: 'a', tekst: '€15,40' }, { id: 'b', tekst: '€17,00' }, { id: 'c', tekst: '€17,50' }, { id: 'd', tekst: '€21,80' }],
    juistAntwoord: 'a',
    uitleg: 'Antwoord a. Perioderesultaat = (P−vk)×V − C → (25−vk)×12.500 − 40.000 = 80.000 → (25−vk) = 9,6 → vk = €15,40.',
    hints: ['Bij VKC: perioderesultaat = (prijs − variabele kosten) × verkopen − constante kosten.', 'Los op naar vk.'],
  }),
  mc({
    id: 'x-2024-dekkingsbijdrage', deel: 2, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.16', difficulty: 'gemiddeld',
    stam: 'De dekkingsbijdrage is het verschil tussen de omzet en:',
    opties: [
      { id: 'a', tekst: 'de variabele standaardkosten van de omzet' },
      { id: 'b', tekst: 'het totaal van de variabele standaardkosten van de periode' },
      { id: 'c', tekst: 'de constante standaardkosten van de omzet' },
      { id: 'd', tekst: 'de totale constante standaardkosten van de periode' },
    ],
    juistAntwoord: 'a',
    uitleg: 'Antwoord a. Dekkingsbijdrage = omzet − variabele kosten van de verkochte (omzet)producten. Variabele kosten van onverkochte producten staan op de balans, niet in het resultaat.',
    hints: ['Dekkingsbijdrage moet de constante kosten dekken → omzet − variabele kosten.', 'Alleen variabele kosten van de verkóchte producten tellen.'],
  }),
  mc({
    id: 'x-2024-normaleprod-progressief', deel: 2, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.15', difficulty: 'lastig',
    stam: 'Variabele kosten zijn progressief stijgend. Na verhóging van de normale productie is de ISKP gestegen. "Deze stijging kan komen door hogere variabele kosten p.e., maar niet door hogere constante kosten p.e." Deze stelling is:',
    opties: [{ id: 'a', tekst: 'Juist' }, { id: 'b', tekst: 'Onjuist' }],
    juistAntwoord: 'a',
    uitleg: 'Antwoord a. Hogere normale productie → constante kosten p.e. dalen (kan de stijging dus niet veroorzaken). Bij progressief stijgende variabele kosten nemen de totale variabele kosten p.e. juist toe bij meer productie → die kunnen de stijging wél verklaren.',
    hints: ['Wat doet de constante-kostencomponent als de noemer groter wordt?', 'Progressief = variabele kosten per extra eenheid lopen op.'],
  }),

  // ===================== DEEL III =====================
  mc({
    id: 'x-2024-budgettype', deel: 3, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.17', difficulty: 'lastig',
    stam: 'Beide maanden: constante kosten aanwezig én alle variabele kosten proportioneel. A. In mei pas je een gemengd budget toe. B. In juni pas je een flexibel budget toe.',
    opties: [{ id: 'a', tekst: 'A en B juist' }, { id: 'b', tekst: 'A juist, B onjuist' }, { id: 'c', tekst: 'A onjuist, B juist' }, { id: 'd', tekst: 'A en B onjuist' }],
    juistAntwoord: 'b',
    uitleg: 'Antwoord b. Een budget met zowel constante als (proportioneel) variabele kosten is een gemengd budget — in beide maanden. Dus B (flexibel) is onjuist.',
    hints: ['Constant + proportioneel variabel samen = welk budgettype?', 'Beide maanden hebben dezelfde structuur.'],
  }),
  mc({
    id: 'x-2024-totaalverschil', deel: 3, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.18', difficulty: 'lastig',
    stam: 'Riet: begroot 200 hoeden × 410 cm × €0,20; werkelijk 215 hoeden × 400 cm × €0,21. Totaal van prijs- + efficiencyverschil op de variabele kosten?',
    opties: [{ id: 'a', tekst: '€1.660 nadelig' }, { id: 'b', tekst: '€840 nadelig' }, { id: 'c', tekst: '€800 nadelig' }, { id: 'd', tekst: '€430 nadelig' }],
    juistAntwoord: 'd',
    uitleg: 'Antwoord d. Ex-post (toegestaan): 215×410×€0,20 = €17.630. Werkelijk: 215×400×€0,21 = €18.060. Totaal verschil = €17.630 − €18.060 = −€430 (nadelig). (Efficiency +€1.230 voordelig, prijs −€1.660 nadelig.)',
    hints: ['Vergelijk de toegestane (ex-post) kosten met de werkelijke kosten.', 'Toegestaan = werkelijke productie × standaard cm × standaardprijs.'],
  }),
  mc({
    id: 'x-2024-vpb', deel: 3, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.19', difficulty: 'lastig',
    stam: 'Voetbalshirts (ISKP). Begroot/normaal: productie 400, verkopen 300, 0,25 m stof à €11, constante kosten €500. Verkoopomvangverschil €300 voordelig; werkelijke verkopen 350. Begrote verkoopprijs?',
    opties: [{ id: 'a', tekst: '€9,45' }, { id: 'b', tekst: '€9,55' }, { id: 'c', tekst: '€10,00' }, { id: 'd', tekst: '€11,00' }],
    juistAntwoord: 'c',
    uitleg: 'Antwoord c. KP = 0,25×€11 + €500/400 = €2,75 + €1,25 = €4. Verkoopomvangverschil = (Qw−Qb)×(VPb−KP) → (350−300)×(VPb−4) = 300 → VPb−4 = 6 → VPb = €10.',
    hints: ['Bereken eerst de integrale standaardkostprijs KP.', 'Verkoopomvangverschil = (werkelijke − begrote afzet) × (begrote prijs − KP).'],
  }),
  mc({
    id: 'x-2023-efficiency-kingma', deel: 3, bronCategorie: 'tentamen-2023', bronLabel: 'Tentamen 2023 vr.18', difficulty: 'lastig',
    stam: 'Kingma. Begroot/normaal: 25.000 producten, 1,20 manuur/product, €30/manuur. Werkelijk: 25.300 producten, 1,25 manuur/product, €31/manuur. Nadelig efficiencyverschil op manuren?',
    opties: [{ id: 'a', tekst: '−€50.375' }, { id: 'b', tekst: '−€48.750' }, { id: 'c', tekst: '−€37.950' }, { id: 'd', tekst: '−€31.625' }],
    juistAntwoord: 'c',
    uitleg: 'Antwoord c. Efficiencyverschil = (HS − HW) × PS = (25.300×1,20 − 25.300×1,25) × €30 = (30.360 − 31.625) × €30 = −€37.950.',
    hints: ['Efficiencyverschil = (toegestane uren − werkelijke uren) × standaardprijs.', 'Toegestane uren = werkelijke productie × standaard manuur/product.'],
  }),
  mc({
    id: 'x-2023-welk-getal', deel: 3, bronCategorie: 'tentamen-2023', bronLabel: 'Tentamen 2023 vr.19', difficulty: 'berucht',
    stam: 'Eén getal in de tabel verandert; daardoor veranderen zowel het verkoopomvangverschil als het prijsverschil op manuren. Welk getal? (manuur/product 1,20 of 1,25; kosten/manuur €30 of €31)',
    opties: [{ id: 'a', tekst: '1,20' }, { id: 'b', tekst: '1,25' }, { id: 'c', tekst: '€30' }, { id: 'd', tekst: '€31' }],
    juistAntwoord: 'c',
    uitleg: 'Antwoord c. Verkoopomvangverschil bevat KP, die afhangt van de standaard manuur (1,20) én standaardprijs (€30). Het prijsverschil op manuren = (PS−PW)×HW bevat alleen de standaardprijs €30. Alleen €30 beïnvloedt beide.',
    hints: ['Welk verschil bevat de integrale standaardkostprijs (KP)?', 'Welke standaardwaarde zit zowel in KP als in het prijsverschil op manuren?'],
  }),
  mc({
    id: 'x-2023-vpv-count', deel: 3, bronCategorie: 'tentamen-2023', bronLabel: 'Tentamen 2023 vr.20', difficulty: 'gemiddeld',
    stam: 'Hoeveel van de zes begrote (en normale) getallen beïnvloeden het verkoopprijsverschil?',
    opties: [{ id: 'a', tekst: 'één' }, { id: 'b', tekst: 'twee' }, { id: 'c', tekst: 'drie' }, { id: 'd', tekst: 'vijf' }],
    juistAntwoord: 'a',
    uitleg: 'Antwoord a. Verkoopprijsverschil = (VPw − VPb) × Qw. Slechts één begrote grootheid (de begrote verkoopprijs VPb) zit hierin.',
    hints: ['Schrijf de formule: (werkelijke − begrote prijs) × werkelijke afzet.', 'Welk begróót getal staat in die formule?'],
  }),
  mc({
    id: 'x-2023-expost-budget', deel: 3, bronCategorie: 'tentamen-2023', bronLabel: 'Tentamen 2023 vr.21', difficulty: 'lastig',
    stam: 'Ex-ante: 100 km, 0,07 l/km, €1,80/l (= €12,60). Werkelijk: 110 km, 0,06 l/km, €2,00/l. Wat zijn de totale begrote kosten van het ex-post budget?',
    opties: [{ id: 'a', tekst: '€11,88' }, { id: 'b', tekst: '€12,00' }, { id: 'c', tekst: '€13,86' }, { id: 'd', tekst: '€15,40' }],
    juistAntwoord: 'c',
    uitleg: 'Antwoord c. Ex-post = werkelijke hoeveelheid output × standaardverbruik × standaardprijs: 110 km × 0,07 l/km × €1,80 = 7,70 l × €1,80 = €13,86.',
    hints: ['Ex-post budget = werkelijke output, maar standaard-verbruik en standaard-prijs.', '110 × 0,07 × €1,80.'],
  }),

  // ===================== DEEL IV =====================
  mc({
    id: 'x-2024-levensduur-lineair', deel: 4, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.8', difficulty: 'berucht',
    stam: 'Machine €100.000, 5 jaar. Cumulatieve totale kosten/machine-uren gegeven (econ. levensduur nu 3 jaar). Wat als de waardedaling lineair zou zijn (€20.000/jaar)?',
    opties: [
      { id: 'a', tekst: 'blijft 3 jaar' }, { id: 'b', tekst: 'blijft 4 jaar' },
      { id: 'c', tekst: 'gaat van 3 naar 4 jaar' }, { id: 'd', tekst: 'gaat van 4 naar 3 jaar' },
    ],
    juistAntwoord: 'd',
    uitleg: 'Antwoord d. Met lineaire (gelijkmatige) afschrijving verschuift de waardedaling over de jaren; herberekening van de kosten per machine-uur geeft het laagste punt bij jaar 3 i.p.v. 4. De economische levensduur verschuift dus van 4 naar 3 jaar.',
    hints: ['Herbereken per jaar: (cumulatieve waardedaling + complementaire kosten) ÷ cumulatieve uren.', 'Zoek opnieuw het jaar met de laagste kosten per machine-uur.'],
  }),
  mc({
    id: 'x-2024-incidenteel-cat', deel: 4, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.22', difficulty: 'gemiddeld',
    stam: 'Categorieën: I indirect+variabel, II direct+variabel, III direct+constant, IV indirect+constant. Voldoende capaciteit. Welke kosten zijn relevant voor de minimumprijs van een incidentele order?',
    opties: [{ id: 'a', tekst: 'I en II' }, { id: 'b', tekst: 'III en IV' }, { id: 'c', tekst: 'II en III' }, { id: 'd', tekst: 'I en IV' }],
    juistAntwoord: 'a',
    uitleg: 'Antwoord a. Incidentele order accepteren als prijs > variabele kostprijs (different costs for different purposes). De variabele kosten zijn categorie I (indirect+variabel) en II (direct+variabel); de constante kosten (III, IV) zijn niet relevant.',
    hints: ['Welke kosten zijn relevant bij vrije capaciteit? Alleen de variabele.', 'Variabele kosten = de twee categorieën met "variabel".'],
  }),
  mc({
    id: 'x-2024-gbr', deel: 4, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.23', difficulty: 'lastig',
    stam: 'Machine €175.000, 2 jaar lineair, restwaarde €25.000. Verkoop jaar 1: 10.500, jaar 2: 11.000 stenen à €32. Grondstof+arbeid: jaar1 €250.000, jaar2 €270.000. 25% Vpb. Gemiddelde boekhoudkundige rentabiliteit?',
    opties: [{ id: 'a', tekst: '3,60%' }, { id: 'b', tekst: '4,80%' }, { id: 'c', tekst: '6,75%' }, { id: 'd', tekst: '9,00%' }],
    juistAntwoord: 'c',
    uitleg: 'Antwoord c. Totale winst voor belasting = omzet (€336.000+€352.000) − kosten (€250.000+€270.000) − afschrijving (€175.000−€25.000=€150.000) = €18.000. Na belasting €13.500 → gemiddeld €6.750. Gem. geïnvesteerd vermogen = (€175.000+€25.000)/2 = €100.000. GBR = 6,75%.',
    hints: ['Winst vóór belasting over de hele looptijd; vergeet de afschrijving (aanschaf − restwaarde) niet.', 'GBR = gemiddelde winst na belasting ÷ gemiddeld geïnvesteerd vermogen ((aanschaf+restwaarde)/2).'],
  }),
  mc({
    id: 'x-2024-tvp-ncw', deel: 4, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.24', difficulty: 'lastig',
    stam: 'TVP(1)=4 jaar, NCW(1)=€15.000 bij nieuw (€120.000, restwaarde €30.000). Nu tweedehands €100.000, restwaarde €10.000, verder gelijk (6 jaar lineair). Welke stelling klopt?',
    opties: [
      { id: 'a', tekst: 'TVP2 korter, NCW2 lager' }, { id: 'b', tekst: 'TVP2 korter, NCW2 hoger' },
      { id: 'c', tekst: 'TVP2 langer, NCW2 lager' }, { id: 'd', tekst: 'TVP2 langer, NCW2 hoger' },
    ],
    juistAntwoord: 'b',
    uitleg: 'Antwoord b. Lagere aanschaf (€100.000) → minder terug te verdienen → kortere TVP (restwaarde valt ná de TVP en telt daar niet mee). NCW stijgt: €20.000 minder investeren nu weegt zwaarder dan €20.000 lagere restwaarde in jaar 6 (die contant gemaakt kleiner is).',
    hints: ['Restwaarde komt aan het eind — beïnvloedt die de terugverdientijd?', 'NCW: €20.000 minder nu vs. €20.000 minder restwaarde over 6 jaar (contant gemaakt).'],
  }),
  mc({
    id: 'x-2023-levensduur-stelling', deel: 4, bronCategorie: 'tentamen-2023', bronLabel: 'Tentamen 2023 vr.7', difficulty: 'lastig',
    stam: 'Taxi, economische levensduur 4 jaar. A. De afschrijvingskosten per jaar in jaar 3 moeten lager zijn dan in jaar 5. B. De economische levensduur heet ook wel de relatieve technische levensduur.',
    opties: [{ id: 'a', tekst: 'A en B juist' }, { id: 'b', tekst: 'A juist, B onjuist' }, { id: 'c', tekst: 'A onjuist, B juist' }, { id: 'd', tekst: 'A en B onjuist' }],
    juistAntwoord: 'd',
    uitleg: 'Antwoord d. Niet de afschrijvingskosten maar de tótale kosten (afschrijving + complementair) per machine-/km bepalen de economische levensduur (A onjuist). "Relatieve technische levensduur" is geen economisch begrip; de absolute technische levensduur is wanneer het actief niet meer presteert (B onjuist).',
    hints: ['Wat bepaalt de economische levensduur: afschrijving alleen, of totale kosten per eenheid?', 'Economische levensduur ≠ technische levensduur.'],
  }),
  mc({
    id: 'x-2023-disconto-interest', deel: 4, bronCategorie: 'tentamen-2023', bronLabel: 'Tentamen 2023 vr.10', difficulty: 'lastig',
    stam: 'In hoeveel situaties is het rentepercentage disconto vs. interest? (1) vermogenskosten t.l.v. perioderesultaat, (2) opbrengsten over banktegoeden, (3) opportunity costs eigen vermogen, (4) nettocontantewaarde van een investering.',
    opties: [
      { id: 'a', tekst: '1× disconto, 3× interest' },
      { id: 'b', tekst: '2× disconto, 2× interest' },
      { id: 'c', tekst: '3× disconto, 1× interest' },
    ],
    juistAntwoord: 'a',
    uitleg: 'Antwoord a. Alleen (4) NCW rekent toekomstige waarden terug = disconto. (1), (2) en (3) bepalen toekomstige kosten/opbrengsten over een huidig bedrag = interest.',
    hints: ['Disconto = toekomstige waarde terugrekenen naar nu.', 'Alleen de NCW maakt contant; de rest is interest.'],
  }),
  mc({
    id: 'x-2023-gbr-wandtegels', deel: 4, bronCategorie: 'tentamen-2023', bronLabel: 'Tentamen 2023 vr.24', difficulty: 'lastig',
    stam: 'Machine €100.000, 5 jaar lineair, restwaarde 20%. Afzet 10.000 +2.000/jaar; prijs €15; grondstof €8 + arbeid €5/stuk. 25% Vpb. Gemiddelde boekhoudkundige rentabiliteit?',
    opties: [{ id: 'a', tekst: '10,0%' }, { id: 'b', tekst: '12,0%' }, { id: 'c', tekst: '15,0%' }, { id: 'd', tekst: '22,5%' }],
    juistAntwoord: 'c',
    uitleg: 'Antwoord c. Marge €15−€13 = €2/stuk × (10+12+14+16+18 dzd = 70.000) = €140.000; − afschrijving (€100.000−€20.000)=€80.000 → winst voor belasting €60.000. Na belasting €45.000, gemiddeld €9.000. Gem. vermogen (€100.000+€20.000)/2 = €60.000. GBR = 15%.',
    hints: ['Dekkingsbijdrage per stuk × totale afzet over 5 jaar − afschrijving = winst voor belasting.', 'GBR = gem. winst na belasting ÷ gem. geïnvesteerd vermogen.'],
  }),
  mc({
    id: 'x-2023-gbr-tvp-spreiding', deel: 4, bronCategorie: 'tentamen-2023', bronLabel: 'Tentamen 2023 vr.25', difficulty: 'berucht',
    stam: 'Zelfde investering, maar afschrijving per stuk (naar rato afzet) i.p.v. lineair. A. GBR(2) lager dan GBR(1). B. TVP(2) korter dan TVP(1).',
    opties: [{ id: 'a', tekst: 'A en B juist' }, { id: 'b', tekst: 'A juist, B onjuist' }, { id: 'c', tekst: 'A onjuist, B juist' }, { id: 'd', tekst: 'A en B onjuist' }],
    juistAntwoord: 'd',
    uitleg: 'Antwoord d. GBR blijft gelijk: totale winst/rendement verandert niet door andere spreiding (A onjuist). Per-stuk afschrijven schuift kosten naar latere jaren → vroeg meer winst/belasting → nettogeldontvangsten later → TVP wordt langer, niet korter (B onjuist).',
    hints: ['Verandert de tótale winst door andere afschrijvingsspreiding?', 'Vroeg meer winst → vroeg meer belasting → terugverdientijd langer.'],
  }),

  // ===================== DEEL V =====================
  mc({
    id: 'x-2024-centra', deel: 5, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.3', difficulty: 'lastig',
    stam: 'Kosten- en opbrengstencentra, condities vervuld, sturen op effectiviteit en efficiency. Waarvan krijgt de directie GÉÉN goed beeld?',
    opties: [
      { id: 'a', tekst: 'efficiency van het kostencentrum' },
      { id: 'b', tekst: 'effectiviteit van het kostencentrum' },
      { id: 'c', tekst: 'efficiency van het opbrengstencentrum' },
      { id: 'd', tekst: 'effectiviteit van het opbrengstencentrum' },
    ],
    juistAntwoord: 'c',
    uitleg: 'Antwoord c. Effectiviteit van een opbrengstencentrum is meetbaar (aantallen/prijzen vs. budget), maar de efficiency (verkoopinspanning vs. prestatie) is niet goed te beoordelen. Bij een kostencentrum zijn input, output én hun relatie bekend → beide meetbaar.',
    hints: ['Een opbrengstencentrum stuurt op omzet; valt de verkoop-inspanning goed te meten?', 'Bij een kostencentrum zijn input-outputrelaties bekend.'],
  }),
  mc({
    id: 'x-2024-roi-bombari', deel: 5, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.4', difficulty: 'gemiddeld',
    stam: 'Bombari A/B/C/D — winst 32/40/28/25, vermogen 500/600/280/400. Hoeveel divisies hebben een ROI hoger dan de onderneming als geheel?',
    opties: [{ id: 'a', tekst: '1' }, { id: 'b', tekst: '2' }, { id: 'c', tekst: '3' }, { id: 'd', tekst: '4' }],
    juistAntwoord: 'a',
    uitleg: 'Antwoord a. ROI: A 6,4%, B 6,67%, C 10%, D 6,25%. Onderneming = 125/1.780 = 7,02%. Alleen C ligt erboven.',
    hints: ['ROI = winst ÷ vermogen per divisie.', 'Onderneming-ROI = totale winst ÷ totaal vermogen.'],
  }),
  mc({
    id: 'x-2024-ri-cronen', deel: 5, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.5', difficulty: 'lastig',
    stam: 'Cronen A/B/C/D — winst 32/40/28/25, vermogen 500/600/380/400, vereist rendement 7%. Hoeveel divisies hebben een negatief (nadelig) residual income?',
    opties: [{ id: 'a', tekst: '1' }, { id: 'b', tekst: '2' }, { id: 'c', tekst: '3' }, { id: 'd', tekst: '4' }],
    juistAntwoord: 'c',
    uitleg: 'Antwoord c. RI = winst − 7%×vermogen: A 32−35=−3; B 40−42=−2; C 28−26,6=+1,4; D 25−28=−3. Drie negatief (A, B, D).',
    hints: ['RI = winst − (vereist rendement × vermogen) per divisie.', 'Tel hoeveel er onder nul uitkomen.'],
  }),
  mc({
    id: 'x-2023-ri-hoogste', deel: 5, bronCategorie: 'tentamen-2023', bronLabel: 'Tentamen 2023 vr.4', difficulty: 'lastig',
    stam: 'Vier divisies, vereist rendement 10%. ROI = omloopsnelheid × winstmarge. A: 8%×1,60, vermogen 6.250. B: 7,5%×1,92, vermogen 5.000. C: 7,75%×1,60, vermogen 10.000. D: 13,75%×0,80, vermogen 20.000. Welke divisie heeft het hoogste RI?',
    opties: [{ id: 'a', tekst: 'A' }, { id: 'b', tekst: 'B' }, { id: 'c', tekst: 'C' }, { id: 'd', tekst: 'D' }],
    juistAntwoord: 'c',
    uitleg: 'Antwoord c. ROI: A 12,8%, B 14,4%, C 12,4%, D 11%. RI = (ROI−10%)×vermogen: A 175, B 220, C 240, D 200. C is het hoogst.',
    hints: ['ROI = winstmarge × omloopsnelheid.', 'RI = (ROI − vereiste ROI) × geïnvesteerd vermogen — let op het grote vermogen van C.'],
  }),
  mc({
    id: 'x-2023-winst-b', deel: 5, bronCategorie: 'tentamen-2023', bronLabel: 'Tentamen 2023 vr.5', difficulty: 'lastig',
    stam: 'Divisies A/B/C — winst 300/?/480, vermogen 1.200/1.200/3.600. ROI van B is twee keer die van de hele onderneming. Winst van B?',
    opties: [{ id: 'a', tekst: '€390 mln' }, { id: 'b', tekst: '€460 mln' }, { id: 'c', tekst: '€520 mln' }, { id: 'd', tekst: '€624 mln' }],
    juistAntwoord: 'c',
    uitleg: 'Antwoord c. (780 + winstB)/6.000 × 2 = winstB/1.200. Oplossen → winstB = €520 mln.',
    hints: ['ROI onderneming = (300+B+480)/(1.200+1.200+3.600).', 'Zet ROI_B = 2 × ROI_onderneming en los op.'],
  }),
  mc({
    id: 'x-2023-ri-procentueel', deel: 5, bronCategorie: 'tentamen-2023', bronLabel: 'Tentamen 2023 vr.6', difficulty: 'lastig',
    stam: '"Als de vereiste ROI van 10% naar 12,5% gaat voor alle divisies, neemt het RI van elke divisie met 25% af." Deze stelling is:',
    opties: [{ id: 'a', tekst: 'juist' }, { id: 'b', tekst: 'onjuist' }],
    juistAntwoord: 'b',
    uitleg: 'Antwoord b. RI is een absoluut bedrag, ROI relatief. De vereiste winst stijgt met 25%, maar de procentuele afname van het RI verschilt per divisie (afhankelijk van werkelijke winst en vermogen).',
    hints: ['RI is absoluut (€), niet relatief (%).', 'Eenzelfde stijging in vereiste winst werkt per divisie anders door in het RI.'],
  }),

  // ===================== DEEL VI =====================
  mc({
    id: 'x-2024-perioderesultaat-iskp', deel: 6, bronCategorie: 'hertentamen-2024', bronLabel: 'Hertentamen 2024 vr.13', difficulty: 'lastig',
    stam: 'Crompouce (ISKP). Werkelijk 250.000, normaal 200.000, verkopen 240.000. Constante kosten €300.000, variabele €1,40/stuk, prijs €4,00. Perioderesultaat?',
    opties: [{ id: 'a', tekst: '€264.000' }, { id: 'b', tekst: '€324.000' }, { id: 'c', tekst: '€339.000' }, { id: 'd', tekst: '€350.000' }],
    juistAntwoord: 'c',
    uitleg: 'Antwoord c. CK p.e. = €300.000/200.000 = €1,50 → ISKP €2,90. Transactieresultaat = 240.000×(€4,00−€2,90) = €264.000. Bezettingsresultaat = (250.000−200.000)×€1,50 = €75.000. Perioderesultaat = €264.000 + €75.000 = €339.000.',
    hints: ['Perioderesultaat (ISKP) = transactieresultaat + bezettingsresultaat.', 'Transactieresultaat = verkopen × (prijs − ISKP); bezetting = (werkelijk−normaal) × CK p.e.'],
  }),
  mc({
    id: 'x-2023-perioderesultaat-vkc', deel: 6, bronCategorie: 'tentamen-2023', bronLabel: 'Tentamen 2023 vr.15', difficulty: 'lastig',
    stam: 'Eberhart BV (VKC). Werkelijk 11.150, normaal 11.200, verkopen 11.050. Constante kosten €42.000, variabele €8,25/stuk, prijs €12,80. Voordelig perioderesultaat?',
    opties: [{ id: 'a', tekst: '€8.277,50' }, { id: 'b', tekst: '€8.652,50' }, { id: 'c', tekst: '€8.732,50' }, { id: 'd', tekst: '€8.840,50' }],
    juistAntwoord: 'a',
    uitleg: 'Antwoord a. VKC: dekkingsbijdrage = (€12,80−€8,25)×11.050 = €50.277,50; − constante kosten €42.000 = €8.277,50. (Productie speelt geen rol bij VKC.)',
    hints: ['Bij VKC telt alleen de verkochte hoeveelheid.', 'Dekkingsbijdrage = (prijs − variabele kosten) × verkopen, minus constante kosten.'],
  }),
  mc({
    id: 'x-2023-transactieresultaat', deel: 6, bronCategorie: 'tentamen-2023', bronLabel: 'Tentamen 2023 vr.16', difficulty: 'berucht',
    stam: 'ISKP. Werkelijk 50.000, normaal 48.000, verkopen 49.000. Constante kosten €60.000, variabele €3,00/stuk, break-evenpunt 40.000 stuks. Voordelig transactieresultaat?',
    opties: [{ id: 'a', tekst: '€12.250' }, { id: 'b', tekst: '€13.500' }, { id: 'c', tekst: '€14.750' }, { id: 'd', tekst: '€15.000' }],
    juistAntwoord: 'a',
    uitleg: 'Antwoord a. Break-even 40.000 → te dekken kosten 40.000×€3 + €60.000 = €180.000 → verkoopprijs €4,50. CK p.e. = €60.000/48.000 = €1,25 → ISKP €4,25. Transactieresultaat = 49.000×(€4,50−€4,25) = €12.250.',
    hints: ['Leid eerst de verkoopprijs af uit het break-evenpunt: prijs = totale te dekken kosten ÷ break-even afzet.', 'Transactieresultaat = verkopen × (prijs − ISKP).'],
  }),
  mc({
    id: 'x-2023-productie-plus', deel: 6, bronCategorie: 'tentamen-2023', bronLabel: 'Tentamen 2023 vr.17', difficulty: 'gemiddeld',
    stam: 'ISKP. Stel de werkelijke productie was 1.000 hoger, alle overige gegevens gelijk. Het perioderesultaat zou:',
    opties: [{ id: 'a', tekst: 'zijn gedaald' }, { id: 'b', tekst: 'niet zijn veranderd' }, { id: 'c', tekst: 'zijn gestegen' }],
    juistAntwoord: 'c',
    uitleg: 'Antwoord c. Meer productie verandert ISKP noch verkopen → transactieresultaat gelijk. Het bezettingsresultaat stijgt (groter positief verschil werkelijk−normaal) → perioderesultaat stijgt.',
    hints: ['Verandert het transactieresultaat door méér produceren (niet meer verkopen)?', 'Meer dan normaal produceren → hoger bezettingsresultaat.'],
  }),
  mc({
    id: 'x-2023-kwadrant-loon', deel: 6, bronCategorie: 'tentamen-2023', bronLabel: 'Tentamen 2023 vr.13', difficulty: 'lastig',
    stam: 'Mei: alleen hamburgers; je loon = helft van (opbrengst − kosten). Juni: ook stroopwafels erbij (door elkaar gebakken). De loonkosten zijn:',
    opties: [
      { id: 'a', tekst: 'niet veranderd van kwadrant: kwadrant I' },
      { id: 'b', tekst: 'verschoven van kwadrant II naar kwadrant I' },
      { id: 'c', tekst: 'niet veranderd van kwadrant: kwadrant II' },
      { id: 'd', tekst: 'verschoven van kwadrant III naar kwadrant IV' },
    ],
    juistAntwoord: 'b',
    uitleg: 'Antwoord b. Loonkosten blijven variabel, maar verschuiven van direct (één product, kwadrant II) naar indirect (twee productgroepen op één bakplaat, kwadrant I).',
    hints: ['Kwadrant II = direct+variabel, I = indirect+variabel.', 'Eén product → direct; twee door elkaar → indirect.'],
  }),
]
